name: CI

on:
  push:
    branches: [ master ]
  schedule:
    - cron: "0 */2 * * *"
  workflow_dispatch:
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

      - name: Docker Image Update Checker
        id: baseupdatecheck
        uses: lucacome/docker-image-update-checker@v1.1.0
        with:
          base-image: library/golang:alpine
          image: yacinesahli/caddy # update for your image

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        if: steps.baseupdatecheck.outputs.needs-updating == 'true'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        if: steps.baseupdatecheck.outputs.needs-updating == 'true'

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        if: steps.baseupdatecheck.outputs.needs-updating == 'true'

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
          push: true
          tags: |
            yacinesahli/caddy:latest
        if: steps.baseupdatecheck.outputs.needs-updating == 'true'
