name: CI

on:
  push:
    branches: [ master ]
  schedule:
    - cron: "0 1 30 * *"
  workflow_dispatch:
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: yacinesahli/caddy
          tags: |
            type=raw,value={{date 'YYYYMMDD'}}

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
          push: true
          tags: yacinesahli/caddy:latest,${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
